language: cpp

compiler:
  - gcc

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7    
    - gcc-7-multilib
    - g++-7-multilib
    - libboost-dev
    - libc6-dev-i386
    - libc6-i386
    - linux-libc-dev:i386
    - cxxtest
    - cmake
  
before_install:
  - echo `getconf _NPROCESSORS_ONLN`
  - lsb_release -c
  - lsb_release -r
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
before_script:
  - cmake --version
  - cmake .
script: 
  - make -j$((2 * `getconf _NPROCESSORS_ONLN`))
  
sudo: false
dist: trusty
