language: cpp

compiler:
  - gcc

before_script:
  - sudo add-apt-repository -y ppa:opencog-dev/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y cxxtest
  - mkdir build
  - cd build
  - cmake ../

script: make
