language: cpp

compiler:
  - gcc

cache:
  apt: true
  directories:
    - ../cmake

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - python-ply
    - libboost-all-dev
    - gcc-multilib
    - gcc-6-multilib
    - g++-multilib
    - g++-6-multilib
    - libc6-dev-i386
    - libc6-i386
    - cxxtest
  
before_install:
  - cat /proc/meminfo
  - echo `getconf _NPROCESSORS_ONLN`
  - lsb_release -c
  - lsb_release -r
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
#  - sudo apt-get --no-install-recommends -y install cmake
  - 'if [ -n "$(find ../cmake/ -prune -empty)" ]; then
     wget https://cmake.org/files/v3.5/cmake-3.5.0.tar.gz;
     tar xf cmake-3.5.0.tar.gz;
     rsync -r --checksum cmake-3.5.0/ ../cmake/;
     fi'
  - cd ../cmake
  - ./configure
  - make -j`getconf _NPROCESSORS_ONLN`
  - dmesg
  - make install
  - cmake --version
  - cd -
before_script:
  - cmake .
script: 
  - make -j`getconf _NPROCESSORS_ONLN`
  
sudo: false
dist: trusty
