language: cpp

compiler:
  - gcc

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55/cmake-3.x
    packages:
    - gcc-6
    - g++-6
    - libboost-dev
    - gcc-multilib
    - gcc-6-multilib
    - g++-multilib
    - g++-6-multilib
    - libc6-dev-i386
    - libc6-i386
    - cxxtest
    - cmake
  
before_install:
  - echo `getconf _NPROCESSORS_ONLN`
  - lsb_release -c
  - lsb_release -r
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
before_script:
  - sed -i '/#define C_DLLEXPORT/c\//#define C_DLLEXPORT' third_party/metamod-hl1/metamod/osdep.h
  - cmake --version
  - cmake .
script: 
  - make -j$((2 * `getconf _NPROCESSORS_ONLN`))
  
sudo: false
dist: trusty
