language: cpp

compiler:
  - gcc

before_script:
  - sudo apt-get -qq update
  - git clone https://github.com/CxxTest/cxxtest.git cxxtest-ro
  - curl -O https://cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.2.3-Linux-x86_64/* /us
  - mkdir build
  - cd build
  - cmake ../

script: make
